### ISSUE TITLE
Highscore-System

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#1]
Ich habe gestern auf der Heimfahrt noch ein Highscore-System zusammengehackt, das aber eine eher rudimentäre Ausgabe hat.

Zur Zeit sammle ich eine Score mit unterschiedlicher Punktzahl pro Gegner sowie die Anzahl der getöteten Gegner (pro Typ).

1) Was wollen wir an Score im laufenden Spiel anzeigen.
2) Wann vergleichen wir die aktuelle Score mit dem Highscore?
3) Wollen wir eine Highscore-Liste mit Spielernamen?

Für 1) würde ich das ganze so lassen, wie es grade ist
Bei 2) könnte man das ganze bei einem **Game Over** anzeigen und auch aktualisieren...

**Comment by simonschreibt-code** [comment]
Im laufenden Spiel könnte man ja den aktuellen und den persönlichen besten Score dieser Session zeigen. Also z.B. 324/833 wobei 324 die aktuelle Punktzahl ist und 833 die persönliche Bestleistung.

Auf dem Gameover-Screen könnte es dann eine Bestenliste geben.

**Comment by mk1x86** [comment]
Highscore kann auch im Hauptmenü angezeigt werden

**Comment by firoball** [comment]
Mein Vorschlag wäre: Statt dem error() Output einfach den GUI Dialog triggern und den Highscore vermelden. Ansonsten einfach im Hauptmenü wie von @mk1x86 vorgeschlagen anzeigen.

**Comment by ikskuh** [comment]
Ich hab mal den Dialog durch den Ingame-Dialog ersetzt, man bekommt jetzt die Highscore-Meldung im Spiel.
Mal gucken, wie ich den Kram ins Hauptmenü bekomme...

**Comment by ikskuh** [comment]
Resolved in e5b97f8598da8303ee99c1f119197cdf725571db, falls jemand was an den Fonts machen möchte, bitteschön, mir reicht das so.
