### ISSUE TITLE
Turrets und Spikes werden nicht mehr rot

### ISSUE THREAD

**Issue by Superku** [Acknex/LottiVersusTheWorld#10]
Mag das jemand fixen, der sich mit der Implementation auskennt?
Sonst guck ich mir das an.

**Comment by simonschreibt-code** [comment]
es sollte eigentlich nicht an der LUT-textur liegen. die habe ich zwar verändert (für die farben auf dem boden) aber die turret-werte habe ich nicht angefasst.

**Comment by ikskuh** [comment]
Hups, da hatte ich nen Copy-Paste-Fehler
