### ISSUE TITLE
Turm hat keine Unterseite

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#13]
Die Todes-Animation scheint geändert zu sein. Jetzt kann man auf jeden Fall die Unterseite der Platte sehen - oder eben nicht, weil dort faces fehlen.

**Comment by xwcg** [comment]
ich glaube bei dir ist was kaputt, hier habe ich immer noch die richtige animation

**Comment by simonschreibt-code** [comment]
Ich glaube Marius meint das hier:
![image](https://user-images.githubusercontent.com/12360416/28558033-41aa3498-7110-11e7-8c4a-2b161662272d.png)

**Comment by mk1x86** [comment]
Genau

**Comment by simonschreibt-code** [comment]
Ich glaube das hier ist so minimal, das kann auch closed werden, oder?
