### ISSUE TITLE
Endgegner-Augen schießen lassen

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#14]
Ich habe mir gedacht, könnte man den Endgegner nicht wie einen Turret behandeln und einfach kontinuierlich Bullets aus den Augen schießen lassen? So wäre er ein bisschen Gefährlich bei minimalen Aufwand :)

**Comment by mk1x86** [comment]
Da der eh einfach auf dem Teleporter hockt, würde ich einfach ein Warnsignal machen und nach zwei Sekunden, macht der Dauerlaser mit den Augen. Dann hält man sich auch vom Teleporter fern, solange er noch nicht gecleared ist. Würde den Gegner dann auch einfach "Guardian" nennen

**Comment by simonschreibt-code** [comment]
Finde ich gut! Ich habe nur das normale Turret-Verhalten vorgeschlagen, damit es nicht zu kompliziert wird. Meine Idee war die Minimal-Implementation aber ich wäre wir jedes Feature on top dankbar :)

Das Umbenennen in Guardian wäre sehr geil!

**Comment by mk1x86** [comment]
Hab mich mal assigned. Hoffe mal, dass ich heute abend Zeit dafür finde

**Comment by simonschreibt-code** [comment]
Evtl. könnten wir auch noch ein elektronisches höhnisches Lachen einbauen oder so. Ein bisschen wie Shodan :D

**Comment by mk1x86** [comment]
fixed
