### ISSUE TITLE
Schwierigkeitsgrad zu lau

### ISSUE THREAD

**Issue by xwcg** [Acknex/LottiVersusTheWorld#15]
Ich musste gerade bis zu stage 9 spielen damit es anfing ein wenig herausfordernd zu werden. Ich würde mal behaupten wir können ausser der anzahl auch die HP der gegner jede stage etwas hochdrehen.

**Comment by ikskuh** [comment]
Interessant! Ich verrecke immer im zweiten oder dritten Level. Spiele aber auch mit dem Nubsie vom Thinkpad.

Was oft stört, ist, dass man manchmal von einer Horde von Gegnern umzingelt wird. Was hier ganz cool wäre: Eine Art Blast-Angriff, der die Gegner von einem wegschleudert

**Comment by mk1x86** [comment]
Finde die Idee gut, aber ich würde nicht noch eine Taste dazu nehmen. Entweder mouse middle oder als Ersatz für die Granate. Wir müssen eigentlich eh irgendwo die Steuerung erklären.

Kann der Generator so angepasst werden, dass zu Beginn keine Gegner in der Nähe sind? Manchmal wird man sofort überrollt

**Comment by xwcg** [comment]
Vielleicht könnten wir die bombe in der reichweite beschränken und dem den push geben. Sogar den schaden etwas runterdrehen? Ich finde die bombe total OP wie sie ist, einfach die gegner kiten und dann alles in einem schlag umhauen ist schon so etwas doof 🤔

**Comment by simonschreibt-code** [comment]
Mein Blast-Angriff heißt Granate :D Aber ich finde die gar nicht so OP, da die Sputniks nicht sofort sterben und naja .. vielleicht spiele ich auch zu schlecht aber ich komme schon in Bedrängnis :D Zumal man die Granate echt nicht oft einsetzen kann.

**Comment by ikskuh** [comment]
Ich glaube, wir könnten das ganze balancen, in dem wir Invicibility-Frames einbauen. Manchmal wird man mit fast 60 Schaden innerhalb kürzester Zeit getroffen...

Mehr HP pro Stage fände ich ganz gut, eventuell auch einfach 5% oder 10% mehr Schaden pro Stage. Mit den I-Frames sollte das dann auch nicht zu übertrieben sein am Anfang

**Comment by mk1x86** [comment]
Wer in Bedrängnis ist, ist selber Schuld. Ich würde keine I-Frames reinnehmen.

**Comment by simonschreibt-code** [comment]
Finde ich auch OK, manchmal hat man einfach Pech bei Rouge-Likes, das gehört irgendwie dazu und da man sehr schnell ein neues Spiel starten kann, stört es auch nicht unbedingt wenn man schnell eine neue Runde spielt.

**Comment by mk1x86** [comment]
Closen?

**Comment by firoball** [comment]
Ich plädiere für zu und ab damit. Spielt sich mittlerweile gut genug :D
