### ISSUE TITLE
Treffer-Feedback für Turm

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#16]
Meint ihr, es wäre möglich die Tower auch weiss aufblitzen zu lassen, wenn man sie trifft? Das Feedback ist super gut bei den Gegnern aber bei den Türmen fehlt es mir noch.

**Comment by mk1x86** [comment]
Scheint noch gar kein Object-Material zu verwenden? Bin da aber nicht drin genug, um das zu korrigieren

**Comment by simonschreibt-code** [comment]
Sie sollten zumindest die Trap-Colors benutzen. @MasterQ32 Kannst du da etwas erkennen bezüglich Code und Zuweisung?

**Comment by ikskuh** [comment]
> Scheint noch gar kein Object-Material zu verwenden?

Die Türme verwenden ein leicht verändertes Boden-Material, damit sie in den Tarn-Modus gehen können. Man könnte hier, ähnlich wie bei den anderen Objekten, ein Aufblitzen erzeugen, dann würde aber auch die Bodenplatte mitblitzen.

Wenn das nicht gewollt ist, braucht man noch eine Alpha-Maske, welche Boden und restlichen Turm separiert

**Comment by mk1x86** [comment]
Dann blitzt halt alles auf, finde ich nicht schlimm

**Comment by simonschreibt-code** [comment]
Ja genau, Gameplay > Grafik. Lass es einfach blitzen :)

**Comment by ikskuh** [comment]
Turm hat Trefferfeedback, Thema abgehakt!

**Comment by simonschreibt-code** [comment]
Gerade ein Problem gesehen: Wenn der Turret blinkt während er stirbt, bleibt er weiss im level :(

![image](https://user-images.githubusercontent.com/12360416/28731099-d50b0928-73d2-11e7-9a7d-4b52e6b9bb5a.png)

**Comment by ikskuh** [comment]
Sollte gefixed sein, plz confirm

**Comment by mk1x86** [comment]
funktioniert, aber neues Issue
