### ISSUE TITLE
Highscore-Counter wird bei Levelwechsel auf 0 zurückgesetzt

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#17]

**Comment by ikskuh** [comment]
Ja, das hatte ich so gelöst, um zu testen, ob man einen Highscore erreichen konnte. Würde die Highscore-Überprüfung einfach in den Game-Over-Screen legen und keinen Reset zwischen den einzelnen Leveln machen.

**Comment by ikskuh** [comment]
Gelöst mit 063dc3a5dc23a69b740bcf23dfeba4efab43f67c
