### ISSUE TITLE
Vorschlag: Steuerung-Tutorial

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#18]
Wir können das Tutorial in den Boden-Text implementieren:

Anfangs wird NICHT Leben/Score angezeigt sondern:

**WASD: Move**

Drückt der Spieler W, A, S oder D wird der Text ausgetauscht:

**Left Mouse: Shoot**

Schießt der Spieler, wird der Text ausgetauscht:

**Right Mouse: Granade**

Sobald der Spieler nun eine Granate feuert ist das Tutorial geschafft und Leben/Score werden angezeigt.

Beim Teleporter wäre ähnliches gut. Wenn der Quest-Geber noch nicht aktiviert wurde, könnte ein Text auftauchen wie in etwa "Inaktiv: Erst mit Questgeber sprechen!".

Was denkt ihr?

**Comment by mk1x86** [comment]
Super Idee, finde ich

**Comment by mk1x86** [comment]
Siehe auch: https://github.com/Acknex/LottiVersusTheWorld/issues/14
In dem Fall:

Teleporter: DISABLED
Guardian: ACTIVE

zu

Telerporter: ACTIVE
Guardian: SHUTDOWN

irgendwie so

**Comment by ikskuh** [comment]
Finde ich ebenfalls gut, so wird das auch leicht verständlich rübergebracht.

**Comment by ikskuh** [comment]
Steuerungs-Tutorial wurde in 57a3e4558939ac38713084b72923c76025437fae gelöst.

**Comment by ikskuh** [comment]
Teleporter-Info wurde mit 8036f086e8aaddbb9d9ee046dc062d36fc573a43 gelöst.
