### ISSUE TITLE
Intro Sequenz

### ISSUE THREAD

**Issue by xwcg** [Acknex/LottiVersusTheWorld#19]
Ich würde gerne mal ideen sammeln für ne intro sequenz (würde ich definitiv auch selber machen).

Meine idee wäre dass man im splash/menü nach dem klick auf start game eine kamerafahrt macht.
Erst durch lottis arme wo man dann hinter dem beam so rauchwolken hat (so nen soft shader für rauchsprites wäre geil!) wo kleine statische szenen verteilt sind die so im "time freeze" effekt das zeigen was der erzähler dann so labert.

Sonst ideen? Text würde ich später noch machen.

**Comment by mk1x86** [comment]
Ich glaube nicht, dass wir derzeit ne depth map haben, und die brauchen wir für soft particles.

An sich finde ich die Idee sehr cool. Braucht's dann noch Musik?

**Comment by xwcg** [comment]
musik fände ich gut aber lass mich das erstmal machen dann kannst du die musik passend dazu timen :D

**Comment by mk1x86** [comment]
Okay, dann sei dir schon mal bewusst, dass die Hitpoints auf einem Raster sein sollten. Ich gehe einfach mal von 100 BPM, 4/4-Takt aus, weil es wohl was ruhigeres wird. Szenenwechsel etc sollten also auf Vielfachen von 60/100*4 = 2.4 Sekunden auftauchen.

**Comment by xwcg** [comment]
die kamera wird eher von szene zu szene fliegen, da wirds keine scharfen schnitte geben

**Comment by ikskuh** [comment]
> Ich glaube nicht, dass wir derzeit ne depth map haben

Ne, haben wir nicht. Kann man aber sicher auch irgendwas zusammenfaken. Könnte ich mich mal dran versuchen, wenn die Szene steht

**Comment by xwcg** [comment]
wird sowieso dauern da ich erst heut abend wieder dran kann xD

**Comment by simonschreibt-code** [comment]
Wird diese Szene abbrechbar sein? Ich frage nur, weil das sicher cool ist, aber wenn man schnell mal zocken will, will man evtl. nicht jedes mal 30s Intro sehen. :D

**Comment by xwcg** [comment]
natürlich, die menüsequenz ist ja auch abbrechbar

**Comment by xwcg** [comment]
so voice assets sind schonmal fertig, coden fange ich dann morgen mal an

**Comment by xwcg** [comment]
Ich bin bis zum 7. auf LARP; werde danach aber das intro fertig bauen

**Comment by simonschreibt-code** [comment]
Viel Spaß! Ich würde vorschlagen: Diese Woche können alle noch arbeiten, aber sobald du wieder da bist schließen wir alle Issues außer Intro und Highscore und dann tüten wir das ganze ein?

Btw.: HAMMER CREDIT SONG! :) I love it!

**Comment by firoball** [comment]
Wie schauts aus mit dem Intro? Langsam sollten wir echt mal den Release raushauen, und danach dann in Schockstarre verfallen ;)

**Comment by xwcg** [comment]
Würde ich jetzt am wochenende machen, hab sonst noch keine zeit gefunden

**Comment by mk1x86** [comment]
Hendrik ist dran, hat fast alle Bilder fertig

**Comment by ikskuh** [comment]
Ich hab mir das grade mal angeschaut, sieht ja richtig geil aus!

**Comment by ikskuh** [comment]
Wäre hiermit ordentlich ins Spiel integriert.
