### ISSUE TITLE
Death-Screen

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#2]
Wenn der Spieler drauf geht, kommt ja im Moment der Death-Screen, anschließend startet das Spiel erneut.

Wollen wir da nicht lieber danach zurück ins Hauptmenü?

Man könnte auch die Highscores darauf anzeigen

**Comment by simonschreibt-code** [comment]
Ich würde dafür stimmen, dass wir es so lassen wie es ist. Das Spiel ist 
ja sehr iterativ (Spielen, Sterben, Nochmal versuchen) und so erspart 
man sich das Klicken auf "Neues Spiel". Stellt euch mal vor bei 
Super-Meat-Boy hätte man nach jedem Tod wieder ins Menü gemusst. :D Die 
Musik kann übrigens auch einfach durchlaufen - falls sie das nicht jetzt 
schon tut. :D

**Comment by mk1x86** [comment]
Musik sollte eigentlich durchlaufen. Eventuell sollte noch eine ogg Version gemacht werden in der Hoffnung, dass der Sprung beim loopen nicht so krass ist. Eigentlich ist es nämlich perfekt loopbar

**Comment by xwcg** [comment]
Ich wäre ja dafür das man keinen vollbild deathscreen bekommt sondern der bildschirm etwas abdunkelt, das bildchen zu sehen ist und dann ein in-game menü kommt vonwegen "nochmal" oder "exit game" (das ding wieder vom spiel ins menü zu wechseln traue ich mir jetzt nicht zu)

**Comment by simonschreibt-code** [comment]
Bzw. könnte dort die Highscore zu sehen sein.

**Comment by ikskuh** [comment]
Ich denke, so wie es grade ist, ist das völlig ausreichend, oder?
