### ISSUE TITLE
Intro/Menu für 1 Frame sichtbar bevor Fade-In losgeht

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#20]
Hier ist ein Beispiel dafür:

![fadein](https://user-images.githubusercontent.com/12360416/28568375-dd0ed48c-7135-11e7-9c1c-17a4fcfa046a.gif)

**Comment by xwcg** [comment]
Spezifisch ist das aufgetreten als der bloom von irgendwem eingebaut wurde. Kann es sein dass die bloom init die camera auch anschaltet bevor die szene bereit ist? @MasterQ32 @Slin

**Comment by ikskuh** [comment]
Ich habs grade mal getestet, das hat nichts mit dem Bloom zu tun (habe den Init-Aufruf dazu rausgenommen)

**Comment by ikskuh** [comment]
Wurde gefixed, keine Ahnung, was das Problem war.
