### ISSUE TITLE
Guardian ist weg, aber er steht immernoch als "active" da

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#21]
Ich töte den letzten Gegner und der Guardian verschwindet:

![guardian_gone](https://user-images.githubusercontent.com/12360416/28568569-9d4791e4-7136-11e7-939e-78ae6afa2c94.gif)

ABER, es steht immernoch "Guardian Active" da. Erst wenn ich das Item einsammle, wird der Guardian runtergefahren:

![guardian_shutdown](https://user-images.githubusercontent.com/12360416/28568637-cefd541c-7136-11e7-8951-aa0c693e1496.gif)

**Comment by mk1x86** [comment]
Wo ich es gerade sehe: sollte wohl auch eher right button oder right mouse button heißen.
und sollte nur im ersten stage kommen

**Comment by xwcg** [comment]
@mk1x86  Wir könnten auch einfach die konvention von "LMB" und "RMB" benutzen, das sollte jeder checken der schon mal ein computerspiel gezockt hat

**Comment by mk1x86** [comment]
Denke ich auch

**Comment by simonschreibt-code** [comment]
Falls möglich, könnte der Teleporter/Questgeber-Text auch die Text-Farbe vom Player benutzen. Da diese Infos durchaus Gameplay-Relevant sind und derzeit nicht sehr auffällig.

**Comment by ikskuh** [comment]
Habe LMB/RMB umgesetzt, Bug mit "Active/Shut Down" ist gefixed, Farben sind jetzt hell.
