### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#24]
![image](https://user-images.githubusercontent.com/4849383/28587599-0bfdea70-7178-11e7-85ce-ca07ffc3c145.png)
Da läuft irgendwas schief. Kann einer der Shader-Guys mal draufgucken?

**Comment by Slin** [comment]
Jo, da müssen wir die vorderen und hinteren wände getrennt rendern, die hinteren wände mit den meisten Objekten im solid pass und die anderen wände zusammen mit Maske und den meisten anderen dingen mit additivem blending im translucent pass. Außerdem sollten die additiv geblendeten Sachen nicht in den depth buffer schreiben (tut die Maske offenbar...).

**Comment by ikskuh** [comment]
Ja, ich hatte das Problem gestern auch und hab die Maske in Z schreiben lassen, danach sind bei mehreren TEstläufen überhaupt keine sorting-fehler mehr aufgetreten. Man könnte auch die Sortierreihenfolge manuell anpassen (`d3d_entsort = 0`)

**Comment by mk1x86** [comment]
hä? was denn nu?

**Comment by mk1x86** [comment]
Also ich habe das Z-Writing wieder deaktiviert, das macht gar keinen Sinn. Was ich nicht verstehe: Die Wände sind nicht transparent (oder sollten es nicht sein?), trotzdem gibt es da sorting Probleme...

**Comment by simonschreibt-code** [comment]
Meine Vermutung: Es gibt nur ein Wandstück. Damit die Rückseite halbtransparent sein kann, sind auch die Vorderseiten transparent aber eben mit 0%?

**Comment by Slin** [comment]
Es ist eigentlich recht einfach: Erst wird die nicht transparente Seite der Wand gerendert und dann die Transparente Seite und alles andere davor und danach. D.h. transparente Dinge die vor den Wänden gerendert werden (und weil transparent nicht in den Depth buffer schreiben) werden überschrieben und nicht transparente Dinge, die danach gerendert werden überschreiben die transparenten Wände.

Die Lösung ist die Wand zweimal zu rendern, erst den nicht transparenten Teil zusammen mit allem anderen nicht transparenten und dann alles transparente zusammen. Dazu brauchen wir einfach nur die Wand als zwei Entities mit dem gleichen Mesh und unterschiedlichem Material und dann müssen wir konsistent dafür sorgen, dass translucent und solid richtig gesetzt sind.

Ich kann mich demnächst darum kümmern, bin aber bisher nicht dazu gekommen :(

**Comment by mk1x86** [comment]
Ja, Trennung muss sein. Gut zu wissen

**Comment by mk1x86** [comment]
@MasterQ32 machst du das noch? Ich bin in dem Code nicht drin.

**Comment by ikskuh** [comment]
Puh, gute Frage. Ist schon unsäglich scheiße für mich grade, das Spiel zu debuggen, da ich ca. 30-45 SEkunden compilierzeit habe, Wine zickt da unglaublich rum bei Gamestudio. Aber ich kann mich morgen mal ransetzen...

Was muss gemacht werden? (Bitte nochmal korrigeren o.ä.)
- Wände duplizieren
- Wand A mit Shader A versehen, der "früh" gezeichnet wird
- Wand B mit Shader B versehen, der "spät" gezeichnet wird

**Comment by mk1x86** [comment]
nicht duplizieren, auftrennen. Also A alle Vorderseiten, B alle rückseiten. Und den einen einfach im solid pass

**Comment by ikskuh** [comment]
Naja, duplizieren wäre eben ähnliches ergebnis, nur einmal eben mit "front side rendering" und einmal mit "backside rendering". dürfte sich sogar positiv auf die performance auswirken, da nur zweimal das selbe mesh und nicht zwei verschiedene meshes gerendert werden...

**Comment by ikskuh** [comment]
Resolved in 6be57bc23c19840e6a6ac20ddfb926041a7a9db0
