### ISSUE TITLE
Löcher sollten normale Objekt-Farben bekommen

### ISSUE THREAD

**Issue by simonschreibt-code** [Acknex/LottiVersusTheWorld#26]
Da die Löcher keinen Gameplay-Aspekt haben (also z.B. keinen Schaden machen) wäre es besser, wenn sie nicht mehr rot als Farbe benutzen sondern eine der Objekt-Farben aus der LUT.

Was denkt ihr?

**Comment by xwcg** [comment]
Bin dafür

**Comment by mk1x86** [comment]
+1

**Comment by simonschreibt-code** [comment]
Supi :) Nun brauchen wir nur jemanden der Objekt Color 1 oder 2 dafür im Code benutzt. Mal schauen welche Farben besser aussehen :)

![image](https://user-images.githubusercontent.com/12360416/28618161-afacaaea-7203-11e7-8c4b-e3005f30e35c.png)

**Comment by firoball** [comment]
Ich hab noch eine Idee für Löcher die ich gerne ausprobieren würde. Also lasst bitte das Fallen Rot vorerst mal noch. Falls die Idee nicht hinhaut, dann sollten wir das umändern

**Comment by firoball** [comment]
In meiner aktuellen Version bremsen die Löcher die Geschwindigkeit des Spielers - außer man springt rechtzeitig. Hat relativ wenig Einfluss aufs Gameplay, kann aber bei hektischen Situationen ne schöne fiesigkeit entwickeln

**Comment by simonschreibt-code** [comment]
Klingt sehr spannend! Ist es schon eingechecked?

**Comment by firoball** [comment]
Noch nicht gepusht. Vodafone hat mir das Internet gekillt und kriegts nicht mehr zum laufen... -_-Am 27.07.2017 11:24 nachm. schrieb ilegacy <notifications@github.com>:Klingt sehr spannend! Ist es schon eingechecked?

**Comment by firoball** [comment]
Ächz... Ich Krieg nen neuen Kabel Router. Bin also wohl noch ein paar Tage offline. Ich schau Mal ob ich von woanders mein Report pushen kann die Tage. Wenn ich zu lange warte wird der merge richtig ätzend. Ich hab viele kleine fixes in vielen Files gemacht.

**Comment by mk1x86** [comment]
nutz dein Handy als wlan ap? die paar MB werden doch bestimmt gehen

**Comment by firoball** [comment]
Kostet mich Aufpreis. Aber ich finde die Tage ne LösungAm 28.07.2017 2:51 nachm. schrieb mk1x86 <notifications@github.com>:nutz dein Handy als wlan ap? die paar MB werden doch bestimmt gehen

**Comment by mk1x86** [comment]
Hier ist irgendwas passiert. momentan hat das Ding vollkommen falsche Farben

**Comment by firoball** [comment]
Es ist oben bei der entity Action eine seltsame Material Zuweisung bei drin. Ich hab die Mal dringelassen beim merge. Farbe auch bei mir seltsam, Code ist für altes Material angepasst.

**Comment by ikskuh** [comment]
Habe wieder das alte Material zugewiesen, sieht jetzt so wie es ist, gut aus.
