### ISSUE TITLE
Fehlende Sounds für "Quest angenommen" und "Questitem eingesammelt"

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#28]
Im Code (quest.c) sind die Sounds schon angelegt, derzeit werden aber einfach die Turret Sounds verwendet.

**Comment by mk1x86** [comment]
Generischer Sound oder Sprache?

**Comment by firoball** [comment]
Bisher ist für generisch ausgelegt. Reicht auch denke ichAm 27.07.2017 8:12 nachm. schrieb mk1x86 <notifications@github.com>:Generischer Sound oder Sprache?

**Comment by firoball** [comment]
Falls die Sounds bereits existieren, bitte kurz die Filenamen durchgeben, damit ich das anpassen kann

**Comment by mk1x86** [comment]
Nein, kommt morgen

**Comment by mk1x86** [comment]
@firoball 
quest_received.wav, quest_completed.wav
Wäre dann durch

**Comment by firoball** [comment]
Ich denke das hier ist fertig. Ich schließe.
