### ISSUE TITLE
Anpassung Questitems und Questtexte

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#29]
Reminder.

**Comment by ikskuh** [comment]
Ich hab mir da schon Gedanken dazu gemacht, aber die neuen Quest-Objekte sind eher undefiniert. Vielleicht möchte sich @Hen-woll dazu mal äußern, was das eigentlich darstellen soll?

**Comment by firoball** [comment]
Bei mir ist ein einziges Mal der questmaster außerhalb des Levels gespawnt. Ist das sonst noch wem passiert? Haben wir da evtl noch ein Problem mit der prozeduralen positionsermittlung?

**Comment by mk1x86** [comment]
Bei mir noch nie

**Comment by firoball** [comment]
Gibt es schon eine Liste der Modelle sowie deren Bezeichnung von @Hen-woll ?
Dann könnte ich die Quests endlich finalisieren.
