### ISSUE TITLE
Add credits to menu

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#3]
Credits szene und Musik fehlt noch

**Comment by xwcg** [comment]
Button ist jetzt im menü drin. @evil-lemming müsstest dann nur noch die SPLASH__startCredits funktion mit deinem code ergänzen

**Comment by mk1x86** [comment]
Musik ist da. @evil-lemming: du bist am Zug

**Comment by simonschreibt-code** [comment]
Da sich hier nicht viel getan hat, schlage ich zwei Varianten vor.

**Minimal**
Wir blenden einfach ein Bild ein, auf dem unsere Namen stehen.

**Bonus**
Wir lassen ein Level erstellen, packen es voller (nicht-feindlicher) Fledermäuse wobei jede einen anderen Namen trägt.

**Comment by ikskuh** [comment]
Ja, den @evil-lemming hats krankheitstechnisch erwischt.

Ich würde am WE einfach ein einfaches Credits-Ding machen (Text-Scroller), wobei mir die Idee mit den Fledermäusen echt gut gefällt!

**Comment by mk1x86** [comment]
Also scroll sollte rein und im infinite typing lottery gab's auch was für getimete Lyrics, das wäre gut

**Comment by ikskuh** [comment]
Joar, würde ich beides "neu" machen...

Für die getimten Lyrics, könntet ihr mir da ein CSV(';') oder ähnliches liefern? Credits würde ich auf ähnlicher Basis basteln, damit wir das ordentlich wiederverwenden können... :)

**Comment by ikskuh** [comment]
Einfach mal böse alle highlighten:
@slin @xwcg @padmalcom  @evil-lemming @firoball @mk1x86 @pjen @ilegacy @Superku @Hen-woll 
Möchtet ihr mit eurem echten Namen, eurem Handle oder beidem in den Credits auftauchen? Ich persönlich würde bevorzugen, dass alle mit "Vorname (Handle) Nachname" in den Credits stehen

**Comment by firoball** [comment]
"" statt ()Am 28.07.2017 11:45 vorm. schrieb Felix Queißner <notifications@github.com>:Einfach mal böse alle highlighten:
@Slin @xwcg @padmalcom  @evil-lemming @firoball @mk1x86 @pjen @ilegacy @Superku @Hen-woll
Möchtet ihr mit eurem echten Namen, eurem Handle oder beidem in den Credits auftauchen? Ich persönlich würde bevorzugen, dass alle mit "Vorname (Handle) Nachname" in den Credits stehen

**Comment by simonschreibt-code** [comment]
Von mir aus OK :) Kannst bei mir gern das machen, da der nick irgendwie verbreiteter ist als ilegacy,

Simon "simonschreibt" Trümpler

**Comment by Superku** [comment]
Jo finde auch die "Vorname (Handle) Nachname" Kombination am besten.

**Comment by ikskuh** [comment]
Credits coding geht btw sehr gut voran, nur @firoball wirft einem mit seinem doofen `type`-define große Steine zwischen die Beine.....
Ich frage mich, warum der Kack die ganze Zeit speicher leakt und einfach nicht ordentlich funktioniert.... Dabei hab ich irgendwo ein 0 byte großes array anstelle eines integers verwendet... GRAH!

![](https://puu.sh/wVnzA/c0a9fe92d1.png)

**Comment by ikskuh** [comment]
Ach ja, @xwcg, was ich noch brauche, wäre eine Funktion, um ins Hauptmenü zurückzukehren... ;)

**Comment by ikskuh** [comment]
Mit dem Commit ebb6149d07a5a2d0cfd360074bfdcebfe1c64338 haben wir jetzt theoretisch funktionierende, grundlegende Credits...

Wer möchte, darf seinen Eintrag in der `credits.dat` gerne noch ein wenig aufblasen und das ganze generell etwas erweitern.

Zudem fände ich wie bei Morbius das ganze mit ein paar Bildeinwürfen ganz cool, haben wir da welche?

**Comment by firoball** [comment]
Hör auf zu meckern und heul nicht rum.Am 28.07.2017 4:06 nachm. schrieb Felix Queißner <notifications@github.com>:Credits coding geht btw sehr gut voran, nur @firoball wirft einem mit seinem doofen type-define große Steine zwischen die Beine.....
Ich frage mich, warum der Kack die ganze Zeit speicher leakt und einfach nicht ordentlich funktioniert.... Dabei hab ich irgendwo ein 0 byte großes array anstelle eines integers verwendet... GRAH!

**Comment by mk1x86** [comment]
Ist mir auch schon passiert mit damage. Für nächstes Jahr wissen wir es besser. dann machen wir defines für skills mit einem s-Prefix und schreiben alle skills in eine Datei, damit wir uns nicht gegenseitig beharken

**Comment by ikskuh** [comment]
Die Skills stehen ja schon in einem File, aber trotzdem sollten etwas bessere Code-Guidelines her. Ich bevorzuge, dass defines in ALLCAPS geschrieben sind, damit man sie gar nicht erst ausversehen "erwischen" kann, ohne daran zu denken. Das ist grade bei multi-programmer-projekten ganz praktisch, zu wissen, ob etwas funktion, variable oder define ist

**Comment by mk1x86** [comment]
Ich schließe jetzt erstmal, weil wir damit eine lauffähige Version haben. Wer noch Zeit investieren möchte, kann das natürlich gerne tun.
