### ISSUE TITLE
In-Game menü

### ISSUE THREAD

**Issue by xwcg** [Acknex/LottiVersusTheWorld#31]
Ein kleines minimales in-game menü

Kriegen wir so nen pause-state hin?

**Comment by ikskuh** [comment]
Habe jetzt ordentliches Escape-Routing eingebaut:

**Im Hauptmenü**: Spiel beendet sich
**In den Credits**: Spiel kehr zurück ins Hauptmenü
**Im Spiel**: Spiel zeigt Game Over Screen, kehrt dann zurück ins Hauptmenü

Für das Intro soll sich @xwcg darum kümmern...

**Comment by mk1x86** [comment]
Intro sind Henrik und ich dran
