### ISSUE TITLE
Ordentliches Escape-Handling

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#33]
Was soll bei Escape passieren?

- Spiel einfach tot?
- Zurück ins Hauptmenü?
- ....

Siehe auch #31 (Ingame-Menü)

**Comment by simonschreibt-code** [comment]
Spontaner Gedanke: Zurück ins Hauptmenu. Dort würde Esc dann das Spie beenden, drückt man es nochmal.

**Comment by mk1x86** [comment]
Ingame menü, resume, exit to system, exit to main menu

**Comment by xwcg** [comment]
gibts hier schon: #31
