### ISSUE TITLE
UI an Auflösung anpassen

### ISSUE THREAD

**Issue by Slin** [Acknex/LottiVersusTheWorld#34]
Menü und UI ist viel zu klein bei hoher Auflösung. Außerdem sind Titel und Game Over Screen ziemlich pixelig und könnte eine deutlich höhere Auflösung vertragen.

**Comment by firoball** [comment]
Splash Auflösung unabhängig hab ich schon eingebaut Am 28.07.2017 4:29 nachm. schrieb Nils Daumann <notifications@github.com>:Menü und UI ist viel zu klein bei hoher Auflösung. Außerdem sind Titel und Game Over Screen ziemlich pixelig und könnte eine deutlich höhere Auflösung vertragen.

**Comment by firoball** [comment]
Ich schau mir das nochmal an, sobald ich die finalen Sounds und Items für die Quests habe.

**Comment by mk1x86** [comment]
Werde ich erst heute Abend zu kommen, weil ich den Tag über unterwegs bin. War gestern noch mit intro und credits beschäftigt

**Comment by firoball** [comment]
Beim Versuch auch die Fonts zu skalieren, kommt irgendein Random Behaviour rein, vermutlich bedingt durch das Setzen der Startauflösung.
Ist das Scaling wirklich so wichtig? Ich tendiere dazu das einfach nicht mehr zu ändern.

**Comment by firoball** [comment]
pan_setdigits mit String als Anzeigeparameter crasht beim zweiten Aufruf. Ganz große Klasse, jcl.
Damit wird das HUD jetzt einfach nicht der Auflösung angepasst. Dialogfenster nicht skalieren, den Emo aber schon, ist noch grausiger als gar nicht skalieren.

zu damit.
