### ISSUE TITLE
Nahkampf-Gegner verbessern

### ISSUE THREAD

**Issue by Slin** [Acknex/LottiVersusTheWorld#35]
Oft treffen diese nicht, auch wenn ich einfach nur da steh und versuche mich treffen zu lassen. Außerdem bleiben sie immer am Teleporter hängen.

**Comment by mk1x86** [comment]
Bats sollten immer treffen, die machen nämlich nur einen Distanzcheck. Das sollten wir bei den anderen vielleicht auch so machen

**Comment by firoball** [comment]
Ist das noch offen? Ich habe das Gefühl, da hat schon jemand dran rumgeschraubt und man wird jetzt öfter getroffen.

**Comment by mk1x86** [comment]
Find's auch okay, closed
