### ISSUE TITLE
Turm kann nicht durch Granate zerstört werden

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#36]

**Comment by firoball** [comment]
Der Event Trigger wird prinzipiell empfangen und manchmal geht das auch. Evtl. Ist das turret Zentrum zu tief?Am 29.07.2017 12:35 vorm. schrieb mk1x86 <notifications@github.com>:

**Comment by simonschreibt-code** [comment]
Also ich habe eben Türme via Granate zerstört ...
