### ISSUE TITLE
Config.h fehlt

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#37]
Netterweise ist die sogar in .gitignore @MasterQ32.
Also am besten mit reinnehmen oder Eintrag entfernen

**Comment by ikskuh** [comment]
Der gedanke der `config.h` ist, dass man damit bequemer seine Debug-Einstellungen haben kann, ohne die jedes mal mitzucommitten bzw. überhaupt das ganze versehentlich machen zu können.

Bei mir stehen folgende Sachen drin:
```c
#define DEBUG
#define FASTLOAD
#define FASTCREDITS
#define WINDOWMODE
```

So wie ich das beobachtet habe, ist es auch "egal", dass die Datei nicht existiert, der Compiler wird zwar meckern, aber weiter machen.

**Comment by mk1x86** [comment]
Ja, ist aber trotzdem komisch. Kann ja von mir aus leer sein, aber da sein sollte sie schon

**Comment by ikskuh** [comment]
Sobald sie halt da ist, kann nicht jeder seine eigene config.h haben, ohne sie irgendwie nervig zu entkoppeln

**Comment by mk1x86** [comment]
Einfach nicht committen, das bekommt man doch wohl hin

**Comment by ikskuh** [comment]
Das wäre aber viel mehr arbeit... *jammer*

**Comment by mk1x86** [comment]
Besser als Code, der eigentlich nicht kompilieren sollte

**Comment by ikskuh** [comment]
So, ich habe jetzt eine Datei angelegt, in der ein mehr aufwändiger Weg steht, wie man das jetzt hinbekommt. Ich werde jeden! Commit der in dieser Datei Änderungen macht, reverten. Egal, was sonst noch dabei ist.
