### ISSUE TITLE
Sputnik versinkt im boden

### ISSUE THREAD

**Issue by xwcg** [Acknex/LottiVersusTheWorld#39]
Aus nem commit von @Hen-woll der es wohl leider nicht gebacken kriegt auf den "new issue" knopf zu drücken:

> Sputnik versinkt leider beim Angriff in den Boden, ich habe die Animation mehrmals überprüft, an der liegt es leider nicht, kann jemand dies im code überprüfen ? Config.h fehlt mir ebenfalls.

**Comment by mk1x86** [comment]
Ich habe ehrlich gesagt nie einen Fehler gesehen

**Comment by firoball** [comment]
Mir ist ebenfalls nie was aufgefallen. Im Zweifelsfall einfach z clampen?Am 30.07.2017 10:28 vorm. schrieb mk1x86 <notifications@github.com>:Ich habe ehrlich gesagt nie einen Fehler gesehen

**Comment by simonschreibt-code** [comment]
Ich glaube mir ist es auch noch nie aufgefallen.

**Comment by ikskuh** [comment]
Fällt mir ebenfalls nicht auf, würde closen
