### ISSUE TITLE
Turret lässt sich oft nicht treffen

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#4]
Da gibt es echt noch Probleme, eigentlich wird er getroffen, aber es ist kein Treffer

**Comment by ikskuh** [comment]
Hm, das könnte in dem Fall nen Problem mit PASSABLE sein...
Ich guck mal, dass ich das mit c_ignore hinbiegen kann

**Comment by ikskuh** [comment]
Gelöst in 3dc045af521004b8acb38287a97cc1b254ffd798
