### ISSUE TITLE
Marker fehlen komplett

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#40]
![](https://puu.sh/wWhhO/135e768310.png)

@firoball seit deinem Merge sehe ich keine Marker mehr.

**Comment by firoball** [comment]
Möglicherweise ist der Auto merge irgendwo schief gegangen. Marker_toggle sollte nur in der init.c hängen... Glaube ich. Konnte nicht testen, müsste blind pushen :oAm 29.07.2017 6:59 nachm. schrieb Felix Queißner <notifications@github.com>:
@firoball seit deinem Merge sehe ich keine Marker mehr.

**Comment by ikskuh** [comment]
fixed
