### ISSUE TITLE
Release Reminder: Auf real fullscreen umstellen

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#42]
Hintergrund: Im Fake Fullscreen verdeckt die Taskleiste das HUD und macht dieses damit ziemlich überflüssig. Außerdem sieht es nicht gut aus.
Fürs Release macht es Sinn, das anzupassen.

Ist eine Möglichkeit vorgesehen, per Menü die Auflösung zu ändern? Ansonsten plädiere ich dafür, die Standard F5/Shift-F5 Funktionalität wieder zu aktivieren

**Comment by mk1x86** [comment]
Easy fix

**Comment by mk1x86** [comment]
fixed in fad155b
