### ISSUE TITLE
Die letzten Dinge, getan werden

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#44]
Henrik macht die Bilder für's Intro, ich werde das noch zusammenstricken. Außerdem würde ich ganz gerne das Credits-Level ändern, das sieht arg langweilig aus und ist was hell. Da sieht man die Schrift schlecht drauf.

**Comment by ikskuh** [comment]
Ich hab @evil-lemming grade gesagt, er möge doch asap mal das WMP hochladen, macht er nach dem Einkaufen...

Wie würdest du das credits-level machen? Man könnte ja auch einfach eine STAGE manuell hartcoden und nicht generieren lassen und dann einfach das als Hintergrund verwenden oder so

**Comment by mk1x86** [comment]
Ne, ich fand die Idee schon gut mit dem runden Raum, aber ich würde halt paar Fotos als Poster an die Wand kleben. Also quasi, wie wir das Spiel entwickelt haben

**Comment by ikskuh** [comment]
Ah, auch ne geile Idee!

**Comment by mk1x86** [comment]
Credits und Intro sind angepasst. Wenn da keiner was dagegen hat, deklariere ich das jetzt als fertig. Wenn @Hen-woll noch Lust hat, können in ein paar Bilder ja noch mehr Details rein

**Comment by evil-lemming** [comment]
Ich hab nochmal was an den Credits geändert. Aus jedem Monitor wackelt einem jetzt der Warlock entgegen.
edit:// Ursprünglich gab es ein Problem damit.

**Comment by mk1x86** [comment]
Kann noch einer der Programmierer das intro richtig verdrahten?

**Comment by ikskuh** [comment]
> Kann noch einer der Programmierer das intro richtig verdrahten?

Was genau soll da gemacht werden?

**Comment by mk1x86** [comment]
Das intro ist momentan auf einem button, aber es sollte mit in start integriert werden. Ich weiß auch nicht, was nach dem intro momentan passiert

**Comment by ikskuh** [comment]
Intro startet jetzt, wenn man ein Spiel aus dem Menü startet... 
 ( 82094edced8f99ef7447fdbeed3ef9a49b24b502 )
