### ISSUE TITLE
Teleporter Sound Endless Loop

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#45]
Wenn man per ESC das Level Richtung Menü verlässt, während man gerade teleportiert, bleibt der Teleportsound dauerhaft hängen.
--> Beim Beenden des Levels sicherstellen, dass der Sound gekillt wird.

**Comment by ikskuh** [comment]
Resolved in 92f15892f5dc2998f27d2e3b3073f07e483e15e0
