### ISSUE TITLE
Kein Release Build möglich!

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#46]
Irgendetwas wurde kürzlich eingebaut, das beim Release Build massive Probleme verursacht. Es wird ein Invalid Pointer in main gemeldet sowie irgendwas mit einer kaputten directive.

Ein Schnellcheck nach relativen Pfaden verlief negativ. Also bitte jeder, der kürzlich irgendwas spezielles eingebaut hat, dringend mithelfen bei der Suche was das sein könnte. Ich habe noch eine verbesserte build.bat eingecheckt, damit der Release Build etwas sauberer vonstatten geht. Die Meldung von fehlenden Dateien könnt ihr ignorieren, das hat mit dem Media Zeug zu tun, das nicht in die Resource rein soll, sondern separat kopiert wird. Aber setzt vor dem Release Build Start unbedingt DEBUG in der config.h, sonst macht es nur pling und ihr seht nix.

Ich muss in meinem Fall jedesmal die Kiste neustarten, weil sich Acknex nicht mehr einkriegt.

**Comment by mk1x86** [comment]
Kann erst heute Nacht gucken, aber werde dann was machen

**Comment by firoball** [comment]
Problem gefunden. Credits.dat muss mitkopiert werden.
-->In Zukunft bitte File Handles auf Gültigkeit überprüfen ;)
