### ISSUE TITLE
Test run: Release candidate #1

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#49]
https://vksbm.de/ackcon/download/lottivstheworld.zip

Bitte ausprobieren, ob das Ding zuverlässig läuft. Auch versuchen, mehrere Levels zu spielen, mehrmals Credits und Intro aufrufen etc.

**Comment by mk1x86** [comment]
Achtung, es ist *lotter* vs...

**Comment by firoball** [comment]
ich hab nur gezippt. Dann heißt das Hauptscript falsch.

**Comment by mk1x86** [comment]
Das kann sein. Welche Größe muss das cover haben?

**Comment by firoball** [comment]
Cover? Das war issue #50 ;)
Kann man in der Winstart Definition in der Haupt WDL beliebig festlegen.

**Comment by firoball** [comment]
Wenn der Release candidate keine Auffälligkeiten zeigt, bau Ich nochmal neu mit dem Starter Screen und umbenannter Main. Ich warte auf eure Rückmeldungen :)Am 15.08.2017 8:17 nachm. schrieb mk1x86 <notifications@github.com>:Das kann sein. Welche Größe muss das cover haben?

**Comment by ikskuh** [comment]
Ich werd heute Abend das ganze mal auf Windows testen, würde übrigens auch vorschlagen, dass wir den Release auch über GitHub festnageln und hochladen...

**Comment by firoball** [comment]
Auf jeden Fall nen Release ziehen. Bisher lagen die binaries dann immer auf indiedb und der Website. Am 16.08.2017 3:06 nachm. schrieb Felix Queißner <notifications@github.com>:Ich werd heute Abend das ganze mal auf Windows testen, würde übrigens auch vorschlagen, dass wir den Release auch über GitHub festnageln und hochladen...

**Comment by mk1x86** [comment]
Kann erst morgen Abend testen

**Comment by firoball** [comment]
Bei mir crasht sporadisch der Build wenn ich das Intro und direkt danach das gestartete Level per ESC abbreche

**Comment by firoball** [comment]
Preloading für das Intro hinzugefügt, Starter Screen drin, Main Script umbenannt. Neuer Release Candidate wird hochgeladen, neue Issue erstellt.
