### ISSUE TITLE
Spikes sollten kein Hindernis für sputniks sein

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#5]
Außerdem kommt der spielt da oft nicht drüber. Kann man die nicht passable machen und der spieler bekommt einfach leben angetroffen? Geht über hit_player

**Comment by mk1x86** [comment]
*der spieler

**Comment by ikskuh** [comment]
Theoretisch sind die Spikes PASSABLE, aber irgendwie zicken die Sputniks da rum. Könnte auch sein, dass das am Pathfinding liegt oder aber an nem c_move.
Ich kümmer mich

**Comment by firoball** [comment]
Spikes hatte ich gestern eigentlich gefixt.... Falls das nicht wieder jemand umgebaut hat...Am 24.07.2017 11:10 vorm. schrieb mk1x86 <notifications@github.com>:Außerdem kommt der spielt da oft nicht drüber. Kann man die nicht passable machen und der spieler bekommt einfach leben angetroffen? Geht über hit_player

**Comment by ikskuh** [comment]
Gelöst in b0012d50043077db83230e09eb69f12127dbed16
Problem waren weder Spikes, Turrets noch Holes, sondern das Level mit Löchern im Kollisionsmesh. Das Mesh hat jeetzt group 30 und die sputniks ignorieren das
