### ISSUE TITLE
Starter screen

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#50]
Wer hat Lust, hier was schönes zu bauen?

Die acknex.wdf Definition kann in der Haupt WDL hinterlegt werden(siehe Morbius).
Wäre aber eher was für den Director's Cut. Ich schreibe diese Issue nur, damit wirs nicht vergessen, sollte noch ein Release kommen.

**Comment by mk1x86** [comment]
Henrik hatte ein gutes Cover

**Comment by firoball** [comment]
so sah das bei Morbius aus:

WINDOW WINSTART
{
  TITLE "Utopia - The Morbius Conspiracy";
  SIZE 359,640;
  MODE IMAGE;	
  BG_COLOR RGB(0, 0, 0);
  BG_PATTERN <morbius.pcx>,OPAQUE;
  PROGRESS RGB(255, 255, 255), 14, 0, 610, 395, 30;
}

Also wider Erwarten kann man wohl auch ungerade Größen nehmen, aber ich hab da irgendwas mit nur pcx und nur 256 Farben im Kopf. Da bin ich mir nimmer sicher. Aber das ist ja schnell konvertiert.

Über SED kann man dann das Starter Window generieren und bekommt ne neue acknex.wdf

**Comment by firoball** [comment]
done.
