### ISSUE TITLE
Test run: Release candidate #2

### ISSUE THREAD

**Issue by firoball** [Acknex/LottiVersusTheWorld#51]
https://vksbm.de/ackcon/download/lottervstheworld.zip

Bitte ausprobieren, ob das Ding zuverlässig läuft. Auch versuchen, mehrere Levels zu spielen, mehrmals Credits und Intro aufrufen etc.

**Comment by firoball** [comment]
"DirectX: ZTARG"
Jemand ne Ahnung auf was diese Popup Meldung hindeuten könnte?

http://www.opserver.de/ubb7/ubbthreads.php?ubb=showflat&Number=337942
das ist relativ wenig hilfreich :D

**Comment by ikskuh** [comment]
Weißt du, wann die aufgetreten ist?

Und noch was anderes: haben wir `fps_max` gesetzt? Meine Grafikkarte hat im Intro volle Auslastung

**Comment by firoball** [comment]
Die DirectX Meldung hab ich beim rumwechseln zwischen Intro Spiel und Credits bekommen. Ich vermute irgendwo ist ein Übergang nicht ganz sauber. Vermutlich eher eklig zu findenAm 17.08.2017 11:37 vorm. schrieb Felix Queißner <notifications@github.com>:Weißt du, wann die aufgetreten ist?
Und noch was anderes: haben wir fps_max gesetzt? Meine Grafikkarte hat im Intro volle Auslastung

**Comment by ikskuh** [comment]
Okay, ich hatte grade einen Absturz, nach einiger Zeit hin und her wechseln zwischen Spiel→Menü→Credits→Menü→Spiel...
Läuft aber an sich stabil genug, dass ich mich damit zufrieden geben würde...

**Comment by firoball** [comment]
Vielleicht kann ja @Slin (oder wer auch immer mit involviert war) nochmal kurz die render targets durchschauen, ob irgendwo etwas nicht aufgeräumt wird. Klingt ja so als wird da irgendwas doppelt gemacht.

**Comment by firoball** [comment]
Wenn sonst keiner mehr Einwände hat, können wir den Link auf das zip heute noch auf die Welt loslassen. Wird langsam Zeit :)Am 17.08.2017 11:57 vorm. schrieb Felix Queißner <notifications@github.com>:Okay, ich hatte grade einen Absturz, nach einiger Zeit hin und her wechseln zwischen Spiel→Menü→Credits→Menü→Spiel...
Läuft aber an sich stabil genug, dass ich mich damit zufrieden geben würde...

**Comment by mk1x86** [comment]
Hatte einen Crash beim anzeigen der highscores nach game over. Habe sonst nichts gemacht. Ich nehme an, es hängt mit dem intro zusammen. Aber egal, hau raus den Kram. Solange man spielen kann, ist okay

**Comment by firoball** [comment]
Das ZIP liegt schon am richtigen Platz. Haut den Link einfach in die Welt. Wer coole Screenshots hat, kann mir die zukommen lassen für die Website.Indiedb müsste noch gepflegt werden, allerdings hab ich heute dafür keine ZeitAm 18.08.2017 8:57 vorm. schrieb mk1x86 <notifications@github.com>:Hatte einen Crash beim anzeigen der highscores nach game over. Habe sonst nichts gemacht. Ich nehme an, es hängt mit dem intro zusammen. Aber egal, hau raus den Kram. Solange man spielen kann, ist okay

**Comment by ikskuh** [comment]
Ich bin mal so frei und close die topic hier. Zudem pack ich noch das lottervstheworld.zip zum github release dazu, dann kann man sich das spiel auch direkt von hier laden
