### ISSUE TITLE
Quest-Dialog-Fenster versperrt Sicht

### ISSUE THREAD

**Issue by mk1x86** [Acknex/LottiVersusTheWorld#6]
Wenn ich gerade in Bedrängnis bin und den NPC berühre, stört die Nachricht.
Sollte entweder nach oben oder nach unten

**Comment by ikskuh** [comment]
Ich pack die mal passender hin. Füge auch gleich noch eine Stage Anzeige ein, welche das aktuelle Level anzeigt

**Comment by ikskuh** [comment]
Gelöst in 394414ae497fde3b07855109ed2847ff52827a4e
