### ISSUE TITLE
Marker-Rework

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#7]
Imho ist der Marker grade zwar konzeptionell ganz cool, sieht aber doof aus und fällt quasi gar nicht auf.

Mein Vorschlag wäre folgendes Design für den Marker:

![](https://puu.sh/wRG4q/8406806027.png)

Das würde inhaltlich immer noch das selbe sein, aber optisch etwas mehr hervorgehoben. Der Marker sollte auch erst angezeigt werden, wenn ein Gegner eine Weile gehovered wurde, damit das ganze nicht beim über den Bildschirm fahren durch die Gegend hoppst.

Das Improvement, dass nur der fokussierte Gegner einen Marker hat, ist schon mal gut.

**Comment by simonschreibt-code** [comment]
Kleine Frage: Wozu brauchen wir so einen Marker überhaupt? Ich bin meißt eher der Fan von Grafik ohne stöhrendes UI, wenn es nicht zwingen erforderlich ist.

**Comment by ikskuh** [comment]
Der gute @firoball will den unbedingt haben. Kann man ja optional machen, ich brauch den auch nicht zwingendermaßen, aber so wie er grade ist, kann ich mich gar nicht damit anfreunden (nur texte)

**Comment by simonschreibt-code** [comment]
Dazu hötte ich noch eine Frage: Kann man Dinge NUR in der Reflektion rendern, aber nicht im eigentlichen Spiel? Evtl könnte man dann Texte in den Boden einbetten. So würden sie die Grafik nicht überlagern und sich in die Grafik einbetten:

![sputnik](https://user-images.githubusercontent.com/12360416/28518858-c16e0576-7069-11e7-8998-b83f39207fa4.png)

**Comment by mk1x86** [comment]
Kann man, aber dann werden die auch geblurred und wären unlesbar

**Comment by firoball** [comment]
Ich würde das tatsächlich einfach halten.Der Rahmen sieht zwar fancy aus, hat aber nach spätestens fünf Minuten Nerv Garantie. Ich werde noch einen Timer für hover enter einbauen. Beeinflusst untouchable das setzen von mouse_ent? Aktuell zickt der hover manchmal weil die Maus über nem Schuss ist...Am 24.07.2017 12:15 nachm. schrieb ilegacy <notifications@github.com>:Dazu hötte ich noch eine Frage: Kann man Dinge NUR in der Reflektion rendern, aber nicht im eigentlichen Spiel? Evtl könnte man dann Texte in den Boden einbetten. So würden sie die Grafik nicht überlagern und sich in die Grafik einbetten:

**Comment by simonschreibt-code** [comment]
Ja, ich finde den Rahmen auch zu viel, wäre aber dafür, dass wir nicht nur simplen Text verwenden. Es sieht dann halt nach debug-menu aus und passt nicht zum Stil des Spiels - und wir haben uns soviel Mühe gegeben die Grafik bisschen schick zu machen, dass es schade wäre, wenn wir jetzt etwas hinzufügen, dass den Stil bricht und auch keinen Zusatznutzen bringt (z.B. im Sinne von Gameplay). 
Ein Anfang wäre zumindest schonmal, wenn man den Text wirklich auf den Boden "legt" sodass er nicht, wie ein gewöhnliches Debug-Menü, im Screenspace positioniert ist. Damit wäre er schonmal in der Welt verortet. Wenn man ihn dann noch halbtransparent macht, könnte es sich ganz gut einbetten. Einziges Problem: Der Text würde über den Rand des Levels hinausragen, wenn ein Gegner an der Kante steht.

**Comment by firoball** [comment]
Meine Güte... Werft es raus und fertig. Keinen Bock mehr... Wird eh alles was ich einbau gleich wieder umgebaut, deaktiviert oder angemeckertAm 24.07.2017 1:16 nachm. schrieb ilegacy <notifications@github.com>:Ja, ich finde den Rahmen auch zu viel, wäre aber dafür, dass wir nicht nur simplen Text verwenden. Es sieht dann halt nach debug-menu aus und passt nicht zum Stil des Spiels - und wir haben uns soviel Mühe gegeben die Grafik bisschen schick zu machen, dass es schade wäre, wenn wir jetzt etwas hinzufügen, dass den Stil bricht und auch keinen Zusatznutzen bringt (z.B. im Sinne von Gameplay).
Ein Anfang wäre zumindest schonmal, wenn man den Text wirklich auf den Boden "legt" sodass er nicht, wie ein gewöhnliches Debug-Menü, im Screenspace positioniert ist. Damit wäre er schonmal in der Welt verortet. Wenn man ihn dann noch halbtransparent macht, könnte es sich ganz gut einbetten. Einziges Problem: Der Text würde über den Rand des Levels hinausragen, wenn ein Gegner an der Kante steht.

**Comment by ikskuh** [comment]
Ich finde die Idee mit dem Text aufm Boden eigentlich ganz geil, ich probier mal aus, wie gut das mit Sprites aussieht
@ilegacy Welche Font hast du in dem Bild oben verwendet?

**Comment by simonschreibt-code** [comment]
@firoball War nicht böse gemeint! Ich finde es um ehrlich zu sein auch nicht gut, wenn einfach so Dinge rausgeworfen werden. Wenn jetzt die Mehrheit etwas nicht gut findet, kann man das ja auch demokratisch entscheiden, aber einfach Dinge wegwerfen ohne dem Ersteller bescheid zu sagen ist nicht die feine Art würde ich sagen. 

@MasterQ32 Die Schriftart kannst du hier finden: http://www.dafont.com/de/minecraftia.font
Aber ich glaube @firoball hatte auch eine nette Schrift gefunden. Die hatte mehr Detail und könnte auch nett aussehen wenn man sie etwas größer auf dem Boden darstellt. Die Schrift könnte ja sogar etwas länger bestehen bleiben als der Gegner selbst. Sozusagen dauert es etwas, bis der SPeicher überschrieben wird, den der Gegner freigegeben hat :D

**Comment by Slin** [comment]
Man könnte auch einfach noch eine Kamera erstellen die nur den Text im sichtbaren Bereich in eine höher aufgelöste Textur rendert und die dann mit auf den Boden projizieren.

**Comment by simonschreibt-code** [comment]
@Slin Klingt super. Übrigens könnte man dann das Leben des Spielers und evtl. Dessen Highscore auch direkt an den Spieler auf den Boden "Kleben" :)

**Comment by mk1x86** [comment]
Ilegacys letzten Kommentar finde ich super!

**Comment by ikskuh** [comment]
Dito. Sollen wir die HUD unten links dann noch behalten?

**Comment by mk1x86** [comment]
Ja. Kann von mir aus sogar größer. Der Kopf ist ja sehr klein

**Comment by simonschreibt-code** [comment]
Jap, der Kopf ist zu cool um den zu löschen :D

**Comment by simonschreibt-code** [comment]
Geiler Fehlermeldung :D 
![image](https://user-images.githubusercontent.com/12360416/28524590-6edd11c2-7081-11e7-8da5-33992b5600dc.png)

**Comment by ikskuh** [comment]
Okay, es geht voran. Ich würde aber die Marker von allen Schüssen entfernen, sonst wird das arg chaotisch

**Comment by ikskuh** [comment]
So, nächster Schritt im Fortschritt: TTB(Text To Boden)-Rendering

![Fortschritt ist gut.](https://puu.sh/wRPla/3ffbfbf027.png)

**Comment by simonschreibt-code** [comment]
Wow cool! Awesome :) Das wirkt doch sofort richtig in-place :)

**Comment by mk1x86** [comment]
Ich sehe irgendwie nur ein halbes Bild :-(

**Comment by ikskuh** [comment]
Das Problem, das ich grade noch habe, ist das Overpainting des TEXT-Objektes. Ich muss irgendwie die `target_map` clearen können... Hilft da ein PANEL?

![](https://puu.sh/wRPHm/e784c6f7aa.png)

**Comment by simonschreibt-code** [comment]
Können wir für Spieler/Enemy Text-Farbe auch Einträge in der LUT-Table machen?

**Comment by mk1x86** [comment]
Ich würde noch die 45° drehen. Sieht aber gut aus

**Comment by ikskuh** [comment]
Theoretisch ja, da muss ich aber mal gucken, wie...

**Comment by ikskuh** [comment]
> Ich würde noch die 45° drehen. Sieht aber gut aus

Ich finde die aktuelle Variante eigentlich ganz cool, weil der Text gut zu lesen ist und halt auch mit dem Level aligned

**Comment by simonschreibt-code** [comment]
Ich finde auch, dass er so für das Level mehr Sinn macht. 45° gedreht wäre dann für den Beobachter aligned :D Ihr könnte ja mal rumtesten, aber spontan wäre ich auch eher für @MasterQ32's version. 

Bezüglich LUT/Color eine Anwort?

**Comment by ikskuh** [comment]
Noch nicht, ich compilier grade erst mal so gefühlte hundert plugins für gimp, inklusive DDS ^^

**Comment by simonschreibt-code** [comment]
hab mal 2 zeilen hinzugefügt und gepushed :)
![image](https://user-images.githubusercontent.com/12360416/28531186-56180a60-7096-11e7-9006-4d6e5f79597c.png)

**Comment by ikskuh** [comment]
Danke dir, es funktioniert auch (im moment so halb)
![](https://puu.sh/wRR71/351f447759.png)

**Comment by simonschreibt-code** [comment]
Sehr cool! Ich könnte dir in der LUT auch noch einen dunkleren Ton geben, damit wir die 0xXXXXXX werte etwas abdimmen. Könnte immernoch stimmig wirken aber etwas den information overflow eindämmen :D

**Comment by ikskuh** [comment]
> Könnte immernoch stimmig wirken aber etwas den information overflow eindämmen

Ne, dafür bräuchte ich zwei TEXT-Objekte pro Objekt, das wäre dann auch wieder etwas Overkill...

Habe die Farben eingebaut, muss aber noch nen Objekt-Shader fixen
![](https://puu.sh/wRRbw/6598fde6d7.png)

**Comment by Slin** [comment]
Wäre glaub ich cool bei Überlappungen die Texte untereinander zu platzieren. Eventuell etwas bloom und fallen sollten glaub ich keinen text haben.

**Comment by ikskuh** [comment]
So, habe jetzt mal einen Stand gepusht, der das Verhalten des vorherigen States komplett mimicts, nur eben auf Basis des neuen Systems... :)

@Slin Wie meinst du "untereinander"? Also quasi nicht die Textzeilen einfach aufeinander packen, sondern stapeln wie bei nem Layouting-System? 

Bloom würde ich nicht machen, das würde die Lesbarkeit zu sehr reduzieren

![](https://puu.sh/wRRC1/ad0d277b98.png)

**Comment by simonschreibt-code** [comment]
sehr cool! wenn du magst, kannst du den bloom aus der LUT-Alpha holen (derzeit schwarz) und dann können wir damit tweaken :) Was komisch ist, die LUT hat für den Text ein reines rot .. aber irgendwie sieht es im SPiel bräunlich aus ... 

du nutzt nicht zufällig zeile 4 für den text statt 6?

**Comment by ikskuh** [comment]
Lese jetzt den Alpha aus der LUT, habe auch noch ein paar Bugfixes hinterhergeschoben.

**Comment by mk1x86** [comment]
auf jeden Fall drehen und viel viel kleiner. Das lenkt noch mehr ab als vorher der Text. 
Max macht da keinen Sinn, das interessiert im Spiel nicht: LIV und SCORE würde ich durch ein Icon ersetzen.
Würde mich auch selber dran setzen, aber mein Kleiner verlangt heute besonders viel Aufmerksamkeit

**Comment by simonschreibt-code** [comment]
sehr cool! übrigens: man könnte das gegner-leben/health natürlich auch noch mit reinpacken :dagger:

**Comment by ikskuh** [comment]
> Das lenkt noch mehr ab als vorher der Text.

Ja, haste auch Recht... Wie viel % kleiner sollten wirs machen?

> LIV und SCORE würde ich durch ein Icon ersetzen. 

Hm, dafür bräuchten wir auch wieder ein PANEL... Wäre dann wohl auch ein Umstieg auf PANEL mit `digit()` anstelle von TEXT, aber ist dann auch kein Problem.

Möchte mal jemand ( @ilegacy zum Beispiel) ein Icon für Score und Leben machen?

**Comment by simonschreibt-code** [comment]
Ich finde die Größe gar nichtmal so schlecht - aber wenn verkleinern, dann vielleicht max 75%?. Hier habe ich mal die Farbe der Gegner abgedimmt - aber sie flasht rot auf wenn man getroffen wird.

![font_01](https://user-images.githubusercontent.com/12360416/28533126-4af61298-709c-11e7-9a98-68011f896920.gif)

**Comment by simonschreibt-code** [comment]
Den score könnten mann theoretisch auf "current/max" schreiben, um eine Zeile zu sparen.

**Comment by ikskuh** [comment]
Das Aufblitzen der "Schrift" kommt daher, dass ich sie Additive auf das reflektierte Bild mappe. Könnte hier auch ein Alpha-Blending zwischen Schrift und Reflektion machen oder zwischen Schrift und normalem Boden oder ...

**Comment by simonschreibt-code** [comment]
finde alles perfekt so wie es ist :) zwei icons sind eingecheckt: 
![image](https://user-images.githubusercontent.com/12360416/28533553-d36c8052-709d-11e7-81df-6621d6a0265c.png)

**Comment by mk1x86** [comment]
Ich finde es halt aufdringlich, wenn eh schon viel los ist. Würde die eventuell bei geringer Distanz zum Spieler ausblenden, damit es dort nicht overkill wird

**Comment by Slin** [comment]
Wenn ich so die überlappenden getweakten farben sehe, find ich es jetzt ziemlich gut. Ich meinte vorhin dass man tatsächlich mit lay outing dann die texte zumindest in der höhe übereinander platziert wenn sie sonst überlappen würden, aber da sah das auch noch doof aus :).

**Comment by Slin** [comment]
Wenn wir weniger anzeigen wollen könnte man überlegen nur die texte für Gegner anzuzeigen die in den letzten paar Sekunden Schaden gemacht oder bekommen haben.

**Comment by simonschreibt-code** [comment]
Irgendwie hat der Player-Text nun dieselbe Farbe wie der Enemy-Text (auf dem Boden). Ist da etwas verrutscht? @MasterQ32

**Comment by ikskuh** [comment]
Habe ich mich grad auch  gefragt. Lass mich mal zu Abend essen, dann guck ich danach

**Comment by ikskuh** [comment]
Gefixt. `player.type` wurde nicht gesetzt

**Comment by ikskuh** [comment]
Ups, falscher Winkel mit 45 Grad versetzt:
![](https://puu.sh/wS20l/2c2f6f4bf0.png)

**Comment by ikskuh** [comment]
So, jetzt mit dem richtigen Winkel:
Ich fand die Version mit *grid alignment* besser als mit *camera alignment*
![](https://puu.sh/wS2gN/087eed14f3.png)

Das Problem ist, dass wir jetzt theoretisch für jeden Gegnertypen ne optische Korrektur für dessen Z-Wert machen müssen, damit der Text perspektivisch neben dem Gegner ist

**Comment by simonschreibt-code** [comment]
Puh also ich fands vorher auch viel besser. Jetzt sieht es wieder UI was nicht zu Welt gehört während es sich vorher perfekt eingebettet hat. Ich konnte auch vorher schon die Player-STats sehr gut lesen. Also von mir aus muss es nicht 45° gedreht sein.

**Comment by ikskuh** [comment]
Lösen wir das doch demokratisch: https://strawpoll.com/89c2sp8x

**Comment by simonschreibt-code** [comment]
Habe abgestimmt :) (Im Notflal könnte man es evtl. vie Options BFG einstellbar machen :D )

**Comment by mk1x86** [comment]
Stimme zu, vorher war besser. Sollte trotzdem viel kleiner sein, der Text ist größer als die Objekte selber

**Comment by ikskuh** [comment]
Hälfte der vorherigen Größe finde ich zu klein:
![](https://puu.sh/wS3sj/68b407e54c.png)

**Comment by simonschreibt-code** [comment]
Würde den Text auch max. auf 75% kleiner machen obwohl ich ihn beim zocken gar nicht störend fand in seiner originalen Größe. Aber kannst es ja mal mit 75-80% probieren? Marius, stört es dich beim Spielen oder gehst du nur von den Screenshots aus? Ich muss sagen, beim SPielen fühlt es sich anders an als auf den statischen Shots.

**Comment by ikskuh** [comment]
Bin jetzt bei einer 60%igen Größe der orginalen Skalierung. Das ist nen guter Kompromiss denke ich. Aktueller Stand ist gepushed in 7a3c2c43e417a80ecb02b72469f1ac18428f71d9

![](https://puu.sh/wS4hR/16ebba61ae.png)

**Comment by mk1x86** [comment]
Fand's beim spielen störend. Könnte auch etwas näher ran an die Objekte

**Comment by ikskuh** [comment]
<strike>*Theoretisch* passen sie sich an die Objektgröße an (`my.max_y` als Distanz), aber scheinbar sind alle Bounding Boxen nicht so pralle</strike>
Oder aber ich bin doof und skaliere anstelle der Größe des Sprites die Größe der Bounding Box. Fix ist up and ready

**Comment by xwcg** [comment]
Sehr geil!!

**Comment by ikskuh** [comment]
Ich denke, die Zufriedenheit passt jetzt. Ich schließ das Topic mal
