### ISSUE TITLE
Score Multiplier einfügen

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#8]
Schnelle Kills in Folge sollten einen Multiplikator ergeben, für das maximale Erlebnis.

Wie soll der funktionieren?

**Comment by simonschreibt-code** [comment]
Spontan würde ich sagen: Eine Killstreak besteht wenn man 2 Gegner innerhalb 1-2 Sekunden getötet hat. Solange man innerhalb je einer weiteren Sekunde mind einen weitere Gegner tötet, get der Multiplier in 0.1 Scritten nach oben?

**Comment by simonschreibt-code** [comment]
Übrigens wird der Score derzeit bei jedem Level_Wechsel wieder auf 0 gesetzt :D

**Comment by ikskuh** [comment]
Multiplier wurde eingefügt (eec5f76b31aa182672a069e988725120cc9f425f). Wird alle 6 Sekunden resettet, steigert sich um 0.1 pro Kill (nicht Treffer, darum auch die 6 Sekunden)
