### ISSUE TITLE
Teleporter-Basis

### ISSUE THREAD

**Issue by ikskuh** [Acknex/LottiVersusTheWorld#9]
Der Teleporter benutzt zur Zeit noch seine eigene Textur und würde gerne auf den Object Shader umsteigen.

Hierzu wird eine angepasste Textur sowie ein 3er-Slot in der LUT benötigt.

**Comment by simonschreibt-code** [comment]
wo ist denn die textur für das gute stück?

**Comment by Hen-woll** [comment]
Entschuldige für die späte Antwort, Die Textur habe ich ins Game/Models/ verzeichnis [Teleport.bmp] getan. die Items habe ich nun auch Fertig , im code müssten die Item Bezeichnungen nun auch abgeändert werden, ich werde gleich damit anfangen ein neues Gameover screen zu erstellen, aufgrund das es mir momentan noch garnicht so gefällt. daraufhin erstelle ich weitere Details meinen haupt modellen,

**Comment by simonschreibt-code** [comment]
Teleport ist vorbereitet. Benutzt irgendwas schon "Object Color 3" in der LUT? Wenn nicht, könnten dir die Farben dort benutzen. Wenn ihr wollt, könnten wir auch Farbe 1 und 2 tauschen, je nachdem ob derTeleporter aktiviert ist oder nicht.

**Comment by ikskuh** [comment]
> Wenn ihr wollt, könnten wir auch Farbe 1 und 2 tauschen, je nachdem ob derTeleporter aktiviert ist oder nicht.

Das ist eher unpraktisch, da wir dafür mal wieder nen neuen Shader bräuchten, und ich eigentlich grade versuche, die Anzahl an Shadern zu reduzieren

> Benutzt irgendwas schon "Object Color 3" in der LUT?

Gute Frage... Könntest die rechte Hälfte der LUT sichtbar machen? Dann muss ich das nicht immer in GIMP von seinem Alphakanal befreien
Ansonsten bekommt der Teleporter jetzt erst mal die OC3 als Farbe

**Comment by simonschreibt-code** [comment]
Das Item (oder gibt es mehere) ist auch vorbereitet. Ich wusste nicht ob ich Textur.bmp oder Textur_fc.bmp nehme sollte aber habe mich einfach mal für letztere entschieden.

**Comment by ikskuh** [comment]
> Das Item (oder gibt es mehere) ist auch vorbereitet.

Die bekommen doch eh den Hologramm-Shader, oder nicht?

@Hen-woll : Du hast die Textur nicht auf "extern" eingestellt, das Modell nutzt noch die alte Textur

**Comment by simonschreibt-code** [comment]
> Gute Frage... Könntest die rechte Hälfte der LUT sichtbar machen? Dann muss ich das nicht immer in GIMP von seinem Alphakanal befreien

Ich glaube das wird schwer, weil dann der Bloom verloren geht, sobald man stirbt und die Textur kurz an das Ende der Farb-Felder springt (und dann langsam wieder an die Anfangs Position springt. Ich kann aber einfach eine LUT_preview speichern, du dann keinen alpha hat. Wäre das ok?

**Comment by ikskuh** [comment]
Ich meinte die Rechte hälfte des Bildes, nicht der Balken ;) Also das, worin der Text steht

**Comment by simonschreibt-code** [comment]
habe mal eine _PREVIEW.BMP hinzugefügt. die wird aut-exported und daher sollte sie immer aktuelle sein :)

**Comment by simonschreibt-code** [comment]
> Ich meinte die Rechte hälfte des Bildes, nicht der Balken ;) Also das, worin der Text steht

ah ok! done :)

**Comment by ikskuh** [comment]
Was man auch machen könnte (und was auch keine edge split faces bräuchte), ist, dass der Spieler sich kurz aufbläht und dann schmilzt... Nur so als Gedanke

**Comment by simonschreibt-code** [comment]
Ich denke wir sind an nem guten Stand und sollten langsam fertig werden. Der Teleport ist schon so super, ich glaube der braucht keine weiteren Features. Close?

**Comment by ikskuh** [comment]
Ich frage mich, was mein Kommentar da zu suchen hat ^^ Eigentlich sollte der zur Todesanimation. 

Fehlt halt nur noch das angepasste Skin

**Comment by simonschreibt-code** [comment]
Was meinst du mit dem Skin? Wir haben die Teleport-Textur umgestellt und der benutzt jetzt das RGB-System :)

**Comment by ikskuh** [comment]
Die Textur benutzt das RGB-System, das Modell nicht:

![](https://puu.sh/wVdDR/ed27b43a2d.png)

Die Textur ist nicht auf "extern" eingestellt, ich ändere das jetzt mal...

**Comment by ikskuh** [comment]
Ingame sieht das ganze mit der richtigen Textur dann so aus:

![](https://puu.sh/wVe1S/8a9b84127d.png)

**Comment by ikskuh** [comment]
Eventuell sollte man die Textur lieber auf PNG mit Alpha umstellen, da im Moment der ganze Teleporter leuchtet

**Comment by simonschreibt-code** [comment]
Die LUT unterstützt auch Alpha und daher sollte man das auch via LUT einstellen können. Ich habe mal extra Teleporter Farben hinzugefügt:

![image](https://user-images.githubusercontent.com/12360416/28713639-2dd34356-7390-11e7-88aa-606cf4207195.png)

Könnten wir das auf diese Farben umstellen? :)

**Comment by ikskuh** [comment]
Dürfte jetzt passen:

![](https://puu.sh/wViFt/b0edf40abc.png)

**Comment by simonschreibt-code** [comment]
Danke sehr! Ich kann das noch ein bisschen tweaken, aber ich denke das Issue können wir schonmal closen :)
